import unittest
import hw567


class TestORF(unittest.TestCase):

    def test_dna_read(self):
        expected_dict = {'AW295329.1': 'TTTTTTTTTTTTTTTTTGGATAATCTAATACATCTTTATTAATCTCAAAATATGTCTTTTTGGTCAATAACATTCTTTTAATAACCATTAAAGATAATCTATTATTAAAAGGTTAATTTTGCTTCCCTTAGATAAATATAACAGAATTCAAATACGAACTTGCCCCGTTCTGTTGAAGTGTAGTGAGAGCTGACTATGTGAACTGAATAATGCTTGTCCTGTACAGAATGGTGAAGAAAAGCAAACTTTTGTTCACCTGGGAACACTTTTTAAAAATACACTGATACTTAACTTAAATAATTGAATACATATCATAAACACACAAATTACACCATTTAAAATATACTTACCTGATACTTAACTTAAATAATTGAATACATATCATAAACACACAAATTACACCATTTAAAATATACTTACTACAAAAAGATCCTGAACATTATTGATTAATGCAAATAAAACTACTTCGCATTATTATAAAAGTCAAAATATTTTACATCACCCTCGTGCCG', 'AW295458.1': 'TTTTTTTTTTTTTTTTTAAGCAAAGTTTAAGTGTTCTTTATGTGTGCTTTTTGTCCCATACCTAAGAAACCATTAAGGCACAGGATTTGAATGAATATCTGGCTCCAGCATTCATGTTCTTAGCCATTACACTACACTGCCTGTCTAGAAACTAAAGGCTGTTAGTAATATTGCACATTAAGTTATTATAAGGGTTTCATGTTGTGAACTAAAAAACACCCATGGGGCAGACACCCTATATTCATCCTCCAACATCAGCATGGACTTCTGAAGGATTCTGGGCTGGAACTGTGATGCCATGTATTAGGGAGAAGGAATGAGGCTCGGGCAAGAGCAGGACTGGTCCCCATGCTGCACACCACACACCACTGTGATCTCCATGTGCTTCCTCTCGGCCGTCACAGTCTCTCCCAAACAGAGATTCACACACAGACACCCCTAATGCTGGGAGGGGTTCACTT'}
        test_data = hw567.SeqIO.parse('./test_data/test_hw5_dnaread.fasta', 'fasta')
        actual_dict = hw567.dna_read(test_data)
        self.assertDictEqual(actual_dict, expected_dict)

    def test_orf_search(self):
        expected_list = ['AW295458.1, 1, 0, 10, MNIWLQHSCS', 'AW295458.1, -1, 2, 12, MLEPDIHSNPVP']
        fasta_dna = hw567.SeqIO.parse('./test_data/test_hw5_chosendna.fasta', 'fasta')
        actual_list = hw567.orf_search(fasta_dna, 10)
        self.assertListEqual(actual_list, expected_list)


if __name__ == "__main__":
  unittest.main()

